### PR TITLE
Refactored the README handling and changed to setuptools from distutils in setup.py

### PR DESCRIPTION
**Pull request by pasztorpisti**
- Today distutils is quite obsolete, I've changed to setuptools. In this case the advantage is that setuptools treats README.rst as a default input while distutils is looking for README or README.txt.
- A little formatting to README.rst to render the code example with python syntax highlight on github and pypi.
- Note that setuptools includes README.rst in the distribution even if you don't include it in MANIFEST.in and pypi would display your README.rst on the pypi page even without reading it and assigning it to `long_description` in the setup.py script.

### CODE REVIEW

**Comment by pasztorpisti** [comment]
I'll have two other pull requests (adding tests, code simplification) in other branches but the changes are unfortunately dependent on each other. I could have added all the changes in one huge pull request but I think processing them one-by-one is usually a good idea.

**Comment by eugene-eeo** [comment]
@pasztorpisti lol, just saw your PR. Apparently our changes are almost identical! Except that I hate double underscores more 😅. Correct me if I'm wrong, but I feel that double underscores aren't really used nowadays, because we assume that programmers are sensible enough to not rely on attributes starting with `_`.

**Comment by pasztorpisti** [comment]
@eugene-eeo I usually use single `_` prefix to mark something as protected inside a class hierarchy, double `__` prefix to mark something as class private, and double `__` prefix AND postfix in case of public/protected/private class attributes that are used by my lower level framework code. I think when it comes to low level framework code that is used by a lot of people then it's better to write your code as if you prepared to deal with psychopaths instead of assuming nice things. :-D

Actually double `__` prefix (without postfix underscores) can be quite useful because python mangles the name of these private symbols so they help avoiding naming conflicts between classes of a class hierarchy but to be honest I also dislike underscores. In case of low level code I survive a few of them though. None of my libraries have made their way to the standard python library so I probably haven't yet earned the privilege to write ugly code and to raise the underscore content of my identifiers near to 50%.

Because of the author's inactivity I've rolled my own dictionary library and I might cancel this PR in the near future.

**Comment by eugene-eeo** [comment]
@pasztorpisti note that you should implement `__contains__`, to avoid needing to catch exceptions from calling your implemented `__getitem__`.

```python
from collections import Mapping
class Map(Mapping):
    def __init__(self, d):
        self.inner = d
    def __getitem__(self, k):
        print('__getitem__(%r)' % (k,))
        return self.inner[k]
    def __iter__(self):
        return iter(self.inner)
    def __len__(self):
        return len(self.inner)

d = Map({1: 'one'})
2 in d
# => __getitem__(2)
```

**Comment by pasztorpisti** [comment]
@eugene-eeo The default implementation of `collections.Mapping.__contains__` catches `KeyError` exceptions. Implementing non-abstract methods of `collections.Mapping` (other than `__getitem__`, `__iter__` and `__len__` as mentioned in [this table](https://docs.python.org/2/library/collections.html#collections-abstract-base-classes)) is only optional optimization. A custom `__contains__` implementation wouldn't bring much in this case: 1 less method call in return for some extra code for you to maintain. I usually optimize only when I have to.

**Pull request merged**
