### PR TITLE
update hash method

### PR DESCRIPTION
**Pull request by AlJohri**
http://stackoverflow.com/questions/10045562/hashing-an-immutable-dictionary-in-python

### CODE REVIEW

**Review by eugene-eeo — CHANGES_REQUESTED** [review]
I'm not very convinced that this would be optimal. It certainly is very elegant, but the memory usage would explode if the dictionary is 'large enough', while the current iteration based version is more frugal.

**Comment by AlJohri** [comment]
It's an iterator

**Comment by AlJohri** [comment]
Oh I see

**Comment by ppolewicz** [comment]
It is only an iterator in Python3. `.items()` produces a list in Python2

but yes, I'd keep it as it is. I think it was actually rewritten from the proposed form to current form in the past..

**Comment by lurch** [comment]
> I think it was actually rewritten from the proposed form to current form in the past..

Yeah, see #13

**Pull request closed without merging**
